### ISSUE TITLE
Getting warning on jekyll serve 

### ISSUE THREAD

**Issue by jitendravyas** [dandenney/emayll#1]
I installed Jekyll and cloned this repo and ran jekyll serve but getting this error. 

```
    Build Warning: Layout 'post' requested in emayll/_posts/2014-05-07-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'default' requested in emayll/index.html does not exist.
```

And this is the output in browser. 

![127 0 0 1 4000 emayll htquj](https://cloud.githubusercontent.com/assets/77309/6078784/df0dc1b8-ae22-11e4-8037-735511c12244.jpg)

**Comment by dandenney** [comment]
I'll create a new version myself to track this down, but I know it's because of the initial Jekyll install files. In the new version, they add a markdown file for you in posts. It also looks like it either overwrote the layout folder or the files didn't pull for some reason.

If you make sure that post.html and default.html are in the layouts folder, it should stop the error.

**Comment by jitendravyas** [comment]
There is no file called post.html inside emayll folder

**Comment by dandenney** [comment]
@jitendravyas yeah, but there _should_ be. I think the Jekyll install overwrote the layouts folder. If you pull and merge or save these 2 files into the folder, it should stop the error: https://github.com/dandenney/emayll/tree/master/_layouts

**Comment by jitendravyas** [comment]
In my last comment I mentined post.html not default.html and email.html. These 2 files are already in _layouts folder

![emall](https://cloud.githubusercontent.com/assets/77309/6080478/bd2b6702-ae37-11e4-9a23-9f1b2b8c1271.jpg)

**Comment by dandenney** [comment]
Ahh, I'm sorry. I was focusing on the error from the index file because I created that.

post.html is being requested by a markdown file created by Jekyll. If you delete _posts/2014-05-07-welcome-to-jekyll.markdown, it will stop requesting it.

**Comment by jitendravyas** [comment]
OK first warning is gone now after deleting the _posts/2014-05-07-welcome-to-jekyll.markdown

But this warning is still there

```
Build Warning: Layout 'default' requested in emayll/index.html does not exist.
```

**Comment by dandenney** [comment]
I'm not sure what could be causing that if default is present. I wiped out my repo and recorded cloning/setup and I can't replicate that.

![emayll](https://cloud.githubusercontent.com/assets/283611/6080680/79520726-ade1-11e4-878a-0cfdf6164497.gif)

**Comment by jitendravyas** [comment]
It's working thanks for this video you have added. I was actually not running jekyll serve at right place
